version: '3'

services:
  mydjangobackend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command:  >
      sh -c "ls &&
             python manage.py makemigrations api &&
             python manage.py migrate &&
             python manage.py loaddata sample.json &&
             python manage.py createsuperuser --noinput --username admin --email example@example.com
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgresql:
            condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=production
      - PROD_DB_ENGINE= 
      - PROD_DB_HOST=postgresql
      - PROD_DB_NAME=main
      - PROD_DB_PORT=5432
      - PROD_DB_USER=postgres
      - PROD_DB_PASSWORD=bureauxlocaux123
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONUNBUFFERED=True
      - DJANGO_SUPERUSER_PASSWORD=1234
    volumes:
      - ./backend/:/backend/
      
  postgresql:
    image: postgres:13.0
    environment:
      - POSTGRES_DB=main
      - POSTGRES_PASSWORD=bureauxlocaux123
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
        - my-datavolume:/var/lib/postgresql/data
        
volumes:
  my-datavolume:
      